modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/gizmo-ds/key-binding-hider-mod/issues"
license = "MIT"

[[mods]]
modId = "key_binding_hider"
version = "${version}"
displayName = "KeyBinding Hider"
authors = "Gizmo"
description = '''
A simple mod for hiding specific key bindings in the GUI.
'''
logoFile = "key_binding_hider-icon.png"

[[dependencies.key_binding_hider]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.key_binding_hider]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

