# suppress inspection "SpellCheckingInspection" for whole file
# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.caching=false
org.gradle.configuration-cache=false
# Mod properties
mod.id=key_binding_hider
mod.name=KeyBinding Hider
mod.group=dev.aika.key_binding_hider
mod.version=1.2.0-beta
mod.enabled_platforms=fabric,neoforge
mod.license=MIT
