modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/gizmo-ds/key-binding-hider-mod/issues"
license = "MIT"

[[mods]]
modId = "key_binding_hider"
version = "${version}"
displayName = "KeyBinding Hider"
authors = "Gizmo"
description = '''
A simple mod for hiding specific key bindings in the GUI.
'''
logoFile = "key_binding_hider-icon.png"

[[dependencies.key_binding_hider]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.key_binding_hider]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "key_binding_hider.mixins.json"
